//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.MarkServiceSoap")]
    public interface MarkServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSubjectDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getSubjectDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSubjectDataTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getSubjectDataTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateSubject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool updateSubject(Client.WS.SubjectClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> updateSubjectAsync(Client.WS.SubjectClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addSubject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int addSubject(Client.WS.SubjectClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<int> addSubjectAsync(Client.WS.SubjectClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteSubject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deleteSubject(Client.WS.SubjectClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteSubjectAsync(Client.WS.SubjectClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudentDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getStudentDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudentDataTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getStudentDataTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool updateStudent(Client.WS.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> updateStudentAsync(Client.WS.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool addStudent(Client.WS.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> addStudentAsync(Client.WS.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deleteStudent(Client.WS.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteStudentAsync(Client.WS.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int get_login(Client.WS.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_login", ReplyAction="*")]
        System.Threading.Tasks.Task<int> get_loginAsync(Client.WS.StudentClass s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMarkDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getMarkDataTable(int sID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMarkDataTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getMarkDataTableAsync(int sID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateMarkList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int updateMarkList(Client.WS.MarkClass[] marks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateMarkList", ReplyAction="*")]
        System.Threading.Tasks.Task<int> updateMarkListAsync(Client.WS.MarkClass[] marks);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubjectClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sIDField;
        
        private string sSubjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int sID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
                this.RaisePropertyChanged("sID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sSubject {
            get {
                return this.sSubjectField;
            }
            set {
                this.sSubjectField = value;
                this.RaisePropertyChanged("sSubject");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MarkClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sNoField;
        
        private int sIDField;
        
        private int mMarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sNo {
            get {
                return this.sNoField;
            }
            set {
                this.sNoField = value;
                this.RaisePropertyChanged("sNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int sID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
                this.RaisePropertyChanged("sID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int mMark {
            get {
                return this.mMarkField;
            }
            set {
                this.mMarkField = value;
                this.RaisePropertyChanged("mMark");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sNoField;
        
        private string sNameField;
        
        private string sPassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sNo {
            get {
                return this.sNoField;
            }
            set {
                this.sNoField = value;
                this.RaisePropertyChanged("sNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName {
            get {
                return this.sNameField;
            }
            set {
                this.sNameField = value;
                this.RaisePropertyChanged("sName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sPass {
            get {
                return this.sPassField;
            }
            set {
                this.sPassField = value;
                this.RaisePropertyChanged("sPass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MarkServiceSoapChannel : Client.WS.MarkServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarkServiceSoapClient : System.ServiceModel.ClientBase<Client.WS.MarkServiceSoap>, Client.WS.MarkServiceSoap {
        
        public MarkServiceSoapClient() {
        }
        
        public MarkServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarkServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarkServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarkServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getSubjectDataTable() {
            return base.Channel.getSubjectDataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getSubjectDataTableAsync() {
            return base.Channel.getSubjectDataTableAsync();
        }
        
        public bool updateSubject(Client.WS.SubjectClass s) {
            return base.Channel.updateSubject(s);
        }
        
        public System.Threading.Tasks.Task<bool> updateSubjectAsync(Client.WS.SubjectClass s) {
            return base.Channel.updateSubjectAsync(s);
        }
        
        public int addSubject(Client.WS.SubjectClass s) {
            return base.Channel.addSubject(s);
        }
        
        public System.Threading.Tasks.Task<int> addSubjectAsync(Client.WS.SubjectClass s) {
            return base.Channel.addSubjectAsync(s);
        }
        
        public bool deleteSubject(Client.WS.SubjectClass s) {
            return base.Channel.deleteSubject(s);
        }
        
        public System.Threading.Tasks.Task<bool> deleteSubjectAsync(Client.WS.SubjectClass s) {
            return base.Channel.deleteSubjectAsync(s);
        }
        
        public System.Data.DataTable getStudentDataTable() {
            return base.Channel.getStudentDataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getStudentDataTableAsync() {
            return base.Channel.getStudentDataTableAsync();
        }
        
        public bool updateStudent(Client.WS.StudentClass s) {
            return base.Channel.updateStudent(s);
        }
        
        public System.Threading.Tasks.Task<bool> updateStudentAsync(Client.WS.StudentClass s) {
            return base.Channel.updateStudentAsync(s);
        }
        
        public bool addStudent(Client.WS.StudentClass s) {
            return base.Channel.addStudent(s);
        }
        
        public System.Threading.Tasks.Task<bool> addStudentAsync(Client.WS.StudentClass s) {
            return base.Channel.addStudentAsync(s);
        }
        
        public bool deleteStudent(Client.WS.StudentClass s) {
            return base.Channel.deleteStudent(s);
        }
        
        public System.Threading.Tasks.Task<bool> deleteStudentAsync(Client.WS.StudentClass s) {
            return base.Channel.deleteStudentAsync(s);
        }
        
        public int get_login(Client.WS.StudentClass s) {
            return base.Channel.get_login(s);
        }
        
        public System.Threading.Tasks.Task<int> get_loginAsync(Client.WS.StudentClass s) {
            return base.Channel.get_loginAsync(s);
        }
        
        public System.Data.DataTable getMarkDataTable(int sID) {
            return base.Channel.getMarkDataTable(sID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getMarkDataTableAsync(int sID) {
            return base.Channel.getMarkDataTableAsync(sID);
        }
        
        public int updateMarkList(Client.WS.MarkClass[] marks) {
            return base.Channel.updateMarkList(marks);
        }
        
        public System.Threading.Tasks.Task<int> updateMarkListAsync(Client.WS.MarkClass[] marks) {
            return base.Channel.updateMarkListAsync(marks);
        }
    }
}
